# Generated by Django 5.1.15 on 2026-03-02 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_alter_tag_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='months_per_year',
            field=models.PositiveSmallIntegerField(choices=[(12, '12 months'), (13, '13 months')], default=12, help_text='Choose 13 if your salary includes a 13th-month payment.'),
        ),
        migrations.AddField(
            model_name='income',
            name='thirteenth_month_bucket',
            field=models.ForeignKey(blank=True, help_text='Saving bucket to allocate the 13th month payment to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finances.savingbucket'),
        ),
        migrations.AddField(
            model_name='income',
            name='thirteenth_month_expense',
            field=models.ForeignKey(blank=True, help_text='Expense to allocate the 13th month payment to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finances.expense'),
        ),
    ]
