# Generated by Django 5.1.15 on 2026-03-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_income_months_per_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_symbol', models.CharField(default='$', help_text='Symbol shown next to amounts, e.g. "$", "€", "£", "Fr."', max_length=8)),
                ('currency_position', models.CharField(choices=[('before', 'Before amount  →  $100.00'), ('after', 'After amount  →  100.00$')], default='before', max_length=6)),
                ('date_format', models.CharField(choices=[('m/d/Y', 'MM/DD/YYYY — 03/02/2026'), ('d/m/Y', 'DD/MM/YYYY — 02/03/2026'), ('Y-m-d', 'YYYY-MM-DD — 2026-03-02'), ('d.m.Y', 'DD.MM.YYYY — 02.03.2026'), ('j F Y', 'D Month YYYY — 2 March 2026'), ('j M Y', 'D Mon YYYY — 2 Mar 2026')], default='m/d/Y', max_length=20)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
