# Generated by Django 5.1.15 on 2026-03-03 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_sitesettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payer',
            field=models.ForeignKey(blank=True, help_text='Who pays this bill upfront. Leave blank if everyone pays their own share directly.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fronted_expenses', to=settings.AUTH_USER_MODEL),
        ),
    ]
