# Generated by Django 5.1.15 on 2026-03-03 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_expense_tags(apps, schema_editor):
    Expense = apps.get_model("finances", "Expense")
    UserExpenseTag = apps.get_model("finances", "UserExpenseTag")
    for expense in Expense.objects.prefetch_related("tags"):
        for tag in expense.tags.all():
            UserExpenseTag.objects.get_or_create(
                user_id=expense.owner_id,
                expense=expense,
                tag=tag,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_expense_payer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExpenseTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tags', to='finances.expense')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_links', to='finances.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'expense', 'tag')},
            },
        ),
        migrations.RunPython(migrate_expense_tags, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='expense',
            name='tags',
        ),
    ]
